"""add organizations support

Revision ID: 6857184110ce
Revises: 
Create Date: 2026-01-28 17:35:06.988451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6857184110ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Criar tabela de organizações
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_document'), 'organizations', ['document'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    
    # 2. Criar organização padrão
    op.execute("""
        INSERT INTO organizations (name, is_active, created_at)
        VALUES ('Organização Padrão', true, now())
    """)
    
    # 3. Adicionar colunas organization_id como nullable primeiro
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('legal_actions', sa.Column('organization_id', sa.Integer(), nullable=True))
    
    # 4. Atualizar registros existentes com a organização padrão
    op.execute("""
        UPDATE users 
        SET organization_id = (SELECT id FROM organizations LIMIT 1)
        WHERE organization_id IS NULL
    """)
    op.execute("""
        UPDATE clients 
        SET organization_id = (SELECT id FROM organizations LIMIT 1)
        WHERE organization_id IS NULL
    """)
    op.execute("""
        UPDATE legal_actions 
        SET organization_id = (SELECT id FROM organizations LIMIT 1)
        WHERE organization_id IS NULL
    """)
    
    # 5. Agora tornar as colunas NOT NULL
    op.alter_column('users', 'organization_id', nullable=False)
    op.alter_column('clients', 'organization_id', nullable=False)
    op.alter_column('legal_actions', 'organization_id', nullable=False)
    
    # 6. Tornar user_id nullable em clients e legal_actions
    op.alter_column('clients', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('legal_actions', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    
    # 7. Criar foreign keys
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'clients', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'legal_actions', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'legal_actions', type_='foreignkey')
    op.alter_column('legal_actions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('legal_actions', 'organization_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.alter_column('clients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('clients', 'organization_id')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_document'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
